### ISSUE TITLE
Manuscript Holds not appearing on Pull List

### ISSUE THREAD

**Issue by todds1vtedu** [bywatersolutions/koha-plugin-storage#24] opened 2018-05-18 19:25 UTC
We set Holds on several boxes of manuscripts in the Burruss collection, e.g. barcode 1002888345, and they do not appear on a pull list.

**Comment by kidclamp** [comment] 2018-05-18 19:39
Did you wait ten minutes? The holds queue is rebuilt every 10 minutes so holds won't appear instantly. If they don't show eventually let me know and I will dig in

**Comment by kidclamp** [comment] 2018-05-18 20:12
I did check back in, I believe the issue is that the items you placed holds on are not holdable because the itemtype is marked as not-for-loan.

While you can override and place holds, the holds queue won't pick them. I am going to need to look into the best way to handle this in the report.

**Comment by todds1vtedu** [comment] 2018-05-22 16:24
This also affects theses/dissertations that are requested, like 1000700123, 1000749665, and 1000749661, which we currently need to send to Tech Services, Debra Simpkins.

**Comment by kidclamp** [comment] 2018-05-22 16:42
So the reason we use the holds queue is because it will pick specific items to fill a record level hold - if these holds will always be one a specific item then I think we can simply have the report look for item level holds on items within the branch that are not on the holds-queue report. 

Will these always be item specific holds?

**Comment by todds1vtedu** [comment] 2018-05-22 19:02
I really don't understand the question because it seems to me that ALL holds are at the item specific level? ...but maybe not?
It seems like my answer is yes though.
Because of your response, it seems like this issue is related to the problem we are having when we have multiple holds (scan requests sometimes) for a single **journal**, but the holds are for a **specific Volume**. Why isn't the hold on the item-level/Volume? Why would one hold be confused with the other Holds on the same journal unless the hold isn't on the Item/Volume?
Are these things not related? Maybe it is immaterial.

**Comment by todds1vtedu** [comment] 2018-05-30 13:52
We are working on this; I think we just need everything on the Pull List that has a Hold. 
I am meeting with Jessica and SPEC to make sure of details.

Technical Services (Debra Simpkins) emailed us saying that they can't get SPEC items delivered to them, but I think she just means we an're pulling them, which is just part of this problem.

She also said they have a limit of 5 items that can put holds on. Do you know if there is a User limit that we need to set for the Technical Services user?

**Comment by todds1vtedu** [comment] 2018-05-30 19:23
This is a much larger issue because patrons cannot request these (SPEC rstor) items. I want to keep this issue open, because Jessica and folks want to do a more global fix by changing the item types and loan rules. They did not want to fix just this Pull Sheet problem and then have to change it to work with whatever they are changing.

**Comment by kidclamp** [comment] 2018-05-30 19:31
Hi Todd, I opened ticket 50429 in our ticketing system to continue this issue there as it is only partially related to the plugin. Once we have resolved things there we can see if follow up is necessary here.

-Nick

**Comment by todds1vtedu** [comment] 2018-05-30 20:35
thank you!

**Comment by kidclamp** [comment] 2018-08-06 17:09
This one is resolved by upated workflows :-)

**Closed as completed by kidclamp** 2018-08-06 17:09 UTC
